---
- hosts: "{{ host }}"

  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
    - name: copy vault file to dest
      copy:
        src: ./files/fichero.encrypt
        dest: /tmp/fichero2.conf
        owner: user
        group: usergroup
        mode: '0644'
        decrypt: true