---
- name: cat file motd
  hosts: all
  tasks:
    - name: return motd to registered var
      command: cat /etc/motd
      register: mymotd

    - name: mostrar mensaje mediante debug module  
      debug: msg="{{mymotd.stdout}}"