---
- name: Install Softwares
  hosts:
  vars:
     packages:
        - name: nginx
          required: True
        - name: mysql
          required: True
        - name: apache
          required: False
  tasks:
  - name: Install "" on Debian
    apt:
      name: ""
      state: present

    when: item.required == True

    loop: ""